### ISSUE TITLE
About qrcode.exceptions.DataOverflowError

### ISSUE THREAD

**Issue by litanlitudan** [lincolnloop/python-qrcode#102]
Hi, I tried to generate a qr code of a string with approximately 2000 characters.
But seems the qrcode doesn't allow me to do so.

Is there any way to handle this problem?
Thank you very much.

**Comment by welshjf** [comment]
Works for me:

````
import qrcode
qr = qrcode.QRCode()
qr.add_data('A'*2000)
qr.make()
````

Maybe you're using multi-byte unicode characters, or explicitly passing a `version` that's too small? But yes, the QR code standard has a maximum size (http://stackoverflow.com/a/11065499/3593941).

**Comment by litanlitudan** [comment]
Sorry for misstatement, the string I was trying to encode was actually 3074 characters.
2000 characters works for me too.

Thank you for the link.
