### ISSUE TITLE
ImportError: No module named qrcode

### ISSUE THREAD

**Issue by TurielD** [lincolnloop/python-qrcode#103]
after installing this module on a Raspberry Pi, I couldn't get the QR generation to work through the command line, nor through a .py script.

It had previously worked with verion 5.1, and installing 5.1 over the 5.3 install solved my issue.

**Comment by SmileyChris** [comment]
You had me worried for a bit there and then I remembered that command is `qr`, not `qrcode`. :dancers:

**Comment by SmileyChris** [comment]
Oh wait, you're saying the import of the qrcode module itself isn't working...? That's odd...

**Comment by SmileyChris** [comment]
It's working fine for me doing a pip install into a Python 2.6 virtualenv. How are you installing it?

**Comment by SmileyChris** [comment]
Closing this issues as "works for me" until I hear some more details

**Comment by aluo1** [comment]
Hi, I met the same problem as TurieID:
    I can use `qr "hello world" > hello.png` through the command line.
    But when I try to `import qrcode` and use `img = qrcode.make("hello world")`, the command line shows some error: `ImportError: No module named 'qrcode'`, I use both `pip install qrcode` and `pip3 install qrcode`,  this problem still exists.

**Comment by welshjf** [comment]
@aluo1 we'll need some more info to make sense of this. For starters could you post the output of:

    head -1 `which qr`
    readlink -f `which python`
    python -c "import sys; print('\n'.join(sys.path))"

**Comment by aluo1** [comment]
Hi, welshjf.
    Thanks for quick reply. Here is the output:
    `#!/usr/local/opt/python3/bin/python3.5`

    `readlink: illegal option -- f
     usage: readlink [-n] [file ...]`

    `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC`

    Again, thank for your awesome library. I used it in command line directly and works great!

**Comment by welshjf** [comment]
OK so original requester was on a Raspberry Pi but you're on a Mac running a local install of Python 3.

If you run "python3.5" I expect the import will work for you.

If you want to use the Mac's builtin Python 2.7 -- probably what's running if you just type "python" -- you'll need to use a "pip" that's running on that interpreter. Perhaps "pip2.7".

**Comment by LenaNoerenberg** [comment]
hi, I know it's been a good three years but I have a similar problem as TurielD and martin-luo. I installed with pip install qrcode and I can use the command line to genreate one.
But when I try to run a simple script like 

```
import qrcode
img = qrcode.make('Some data here')
```

I get this error:
```
Traceback (most recent call last):
  File "/home/pi/generate.py", line 2, in <module>
    import qrcode
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
    module = self._original_import(*args, **kw)
ImportError: No module named 'qrcode'
```

I'm using a Raspberry Pi 3 and python 2.7.
I would be very greateful for any help i can get

**Comment by vikas2dx** [comment]
try this python2.7 -m pip install qrcode , I was facing the same issue, it worked for it

**Comment by dudulyangyang** [comment]
> Hi, I met the same problem as TurieID:
> I can use `qr "hello world" > hello.png` through the command line.
> But when I try to `import qrcode` and use `img = qrcode.make("hello world")`, the command line shows some error: `ImportError: No module named 'qrcode'`, I use both `pip install qrcode` and `pip3 install qrcode`, this problem still exists.

hi marton: did you solve this ? i met the same one today, can you give a hint ? thank you

**Comment by dudulyangyang** [comment]
> Hi, I met the same problem as TurieID:
> I can use `qr "hello world" > hello.png` through the command line.
> But when I try to `import qrcode` and use `img = qrcode.make("hello world")`, the command line shows some error: `ImportError: No module named 'qrcode'`, I use both `pip install qrcode` and `pip3 install qrcode`, this problem still exists.

i can run it via comand line , it works well , but in pycharm , it can not find qrcode module, i don't know why

**Comment by dudulyangyang** [comment]
problem solved， i install qrcode package from pycharm setting, it's working now

**Comment by Tushar-2246** [comment]
try using **pip install qrcode[pil]** It worked for me after a lot of research.

**Comment by Dharmesh-infinite** [comment]
> try using **pip install qrcode[pil]** It worked for me after a lot of research.

None of them worked for me ,can you give me a hint to solve it?

**Comment by Tushar-2246** [comment]
@Dharmesh-infinite please comment your error, which you got in terminal. Maybe I can solve.

**Comment by Dharmesh-infinite** [comment]
> @Dharmesh-infinite please comment your error, which you got in terminal. Maybe I can solve.

"D:\my projects\QR_generator\main.py", line 4, in <module>
    import qrcode
ModuleNotFoundError: No module named 'qrcode'

**Comment by Tushar-2246** [comment]
Please try your code on 
https://www.onlinegdb.com/online_python_compiler
It will definitely help.

**Comment by Tushar-2246** [comment]
Btw it you are beginner in python have a look on my website.
www.basicpythonprogramme.blogspot.com

**Comment by koloyyee** [comment]
I still find the same problem when I use venv, I don't have this import error when pip install global but I have trouble with venv and install through poetry

**Comment by nfaltir** [comment]
I am having the exact same issue running it on vscode. It works when I run it using default terminal. 

error in vscode: "No module named qrcode"

**Comment by itsrabinbhat** [comment]
I'm still facing the same problem
I installed qrcode as `pip install qrcode `
and while importing qrcode in a python file as `import qrcode`

The error occurs: **Import "qrcode" could not be resolved**

**Comment by AlvaroDutra** [comment]
i had this problem and solved it by creating a virtual env. I use visual studio.

**Comment by Hoccyy** [comment]
> https://www.onlinegdb.com/online_python_compiler

This is a good online compiler but it doesn't have the qrcode module required.
