### ISSUE TITLE
Packing RPM with setup.py

### ISSUE THREAD

**Issue by 0xHM** [lincolnloop/python-qrcode#107]
From version 5.1 to latest (tested)

RPM build errors:
    File not found: /home/builder/tmp/python-qrcode-5.1/build/bdist.linux-x86_64/rpm/BUILDROOT/qrcode-5.1-1.x86_64/usr/share/man/man1/qr.1
error: command 'rpmbuild' failed with exit status 1

**Comment by welshjf** [comment]
Looks like a problem in the setuptools/rpmbuild interaction to me. It installs the man page, then compresses it, then expects to find it uncompressed.

My suspicion is that automagic RPM generation is an inherently doomed enterprise and the correct approach, if you want quality RPMs, is to maintain a spec file yourself. However the --spec-only option to bdist_rpm can give you a starting point.

**Comment by SmileyChris** [comment]
Also, `python setup.py bdist_rpm` is working fine for me (with setuptools 26.1.1)

**Comment by welshjf** [comment]
Ah, cool. For the record, I reproduced the issue with setuptools 17.1.1.

**Comment by 0xHM** [comment]
Oh ok nice
