### ISSUE TITLE
How to send text with CR LF to break my text into two or more lines?

### ISSUE THREAD

**Issue by fdoliveira** [lincolnloop/python-qrcode#123]
I want to generate a arcade with two or more lines separated with \r\n, but when I read it appears with 
§r§n. I sent 'TEST\r\n\TEST\r\n\TEST' and receive 'TESTE§r§nTESTE§r§nTESTE'. What char I have to use in string to get new line? like example:
TEST
TEST
TEST

**Comment by sandyCH** [comment]
Hi fdoliveira - I had the same problem with the command line, so I resorted to python3 and the command that prints literally ''' ''' to print a three line QRCode:
**import qrcode
import qrcode.image.svg
factory = qrcode.image.svg.SvgPathImage

img = qrcode.make('''TEST
TEST
TEST''', image_factory=factory)

img.save('test.svg',"SVG")**
