### ISSUE TITLE
import Image error

### ISSUE THREAD

**Issue by walchko** [lincolnloop/python-qrcode#129]
I was trying out your code following an example in your readme. Apparently I need an additional import? Is pil or pillow or something else required? If so, I suggest you add it to your `setup.py` file.

My system is macOS 10.12.2 and you can see the python version below.

``` python
kevin@Logan tmp $ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qrcode 
>>> qr = qrcode.QRCode()
>>> qr.add_data('Linux')
>>> qr.make(fit=True)
>>> img = qr.make_image()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/qrcode/main.py", line 271, in make_image
    from qrcode.image.pil import PilImage
  File "/usr/local/lib/python2.7/site-packages/qrcode/image/pil.py", line 8, in <module>
    import Image
ImportError: No module named Image
>>> 
```

**Comment by SmileyChris** [comment]
The default qr generator uses PIL (as the readme clearly states), but since you can also use other generators it is not an enforced requirement.

**Comment by andkirby** [comment]
So. how to fix it? :) I got Pillow package but still see the error.
