### ISSUE TITLE
Are generated QR Codes ISO/JIS compliant?

### ISSUE THREAD

**Issue by podloucky-init** [lincolnloop/python-qrcode#130]
Hi there,
First of all: Thank you for your work with python-qrcode we are using it successfully in some projects.

The following question came up during a discussion about QR Code licensing which may be of general interest:
Are the QR Codes generated by python-qrcode ISO/JIS compliant?

DENSO WAVE INC. explicitly states that ["Everyone can use the QR Code freely as long as following the standards for QR Codes in JIS or ISO."](http://www.qrcode.com/en/patent.html) Does this apply to python-qrcode? Are there some parameters (version, error correction, etc.) which do not conform to ISO/JIS?

Thanks in advance for your feedback.

**Comment by heuer** [comment]
I think the generated codes are compliant. 

Generators may choose different mask patterns or optimization methods, but the output should be a valid QR Code. The generated code may not be optimal / minimal but valid.
