### ISSUE TITLE
Need to `pip install colorama` on Windows

### ISSUE THREAD

**Issue by wecsam** [lincolnloop/python-qrcode#131]
As I understand it, Colorama is only required on Windows when outputting to the console, so running `pip install qrcode` does not automatically install it. Perhaps we could get a message that says that Colorama must be installed on Windows.

<img width="578" alt="2017-02-07" src="https://cloud.githubusercontent.com/assets/12959957/22716895/03f3c2a0-ed66-11e6-84eb-29d6533785d7.png">

**Comment by kuhne** [comment]
If using the source dist, colorama should be installed due to <https://github.com/lincolnloop/python-qrcode/blob/master/setup.py#L23>

But the wheel dist does not use setup.py so a warning makes sense. Or mark colorama as hard dependency

**Comment by fowlslegs** [comment]
https://www.python.org/dev/peps/pep-0426/#environment-markers seems like the preferred way to do this. I think I caused this bug, so sorry, and I'll make a PR soon to try to fix it (unfortunately can't test as I don't have a Windows machine--maybe there's a way I can mock this).

**Comment by wecsam** [comment]
I have a Windows machine. If I can help test something, let me know.

**Comment by SmileyChris** [comment]
Should be fixed with the changes made to setup.cfg in 310ccec4c36911ccfb49a2d5d7e5e9ae284fa176
