### ISSUE TITLE
How can I script QR code naming

### ISSUE THREAD

**Issue by Jzarecta** [lincolnloop/python-qrcode#134]
I need to generate a loop through a list of strings and generate the filenames for the QR code. My question is if this is an attribute of the ```make_image()```. Or what kind of attributes does the make_image() object shows.

**Comment by SmileyChris** [comment]
`make_image()` provides you with a PIL image that you can then [`.save(with_any_filename)`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.save).
