### ISSUE TITLE
how we can decode a qr-image?

### ISSUE THREAD

**Issue by seyyedmohammadhosseini** [lincolnloop/python-qrcode#135]
Hi Guys,
i want to decode a qr-image but how?
i google it but i just found this code:
`d = qrcode.Decoder()`
but after run:
`AttributeError: 'module' object has no attribute 'Decoder'`
why? i need a way to decode 
:(

**Comment by SmileyChris** [comment]
This library is only for QR encoding. Perhaps https://pypi.python.org/pypi/zbarlight will work for you?

**Comment by seyyedmohammadhosseini** [comment]
Thanks
