### ISSUE TITLE
which is the license? all rights reserved, or BSD?

### ISSUE THREAD

**Issue by mfrasca** [lincolnloop/python-qrcode#138]
the LICENSE file here states "all rights reserved", but the pypi page says it's BSD.
which is the case? 
(I am choosing a library for a GPL licensed program.)

**Comment by mfrasca** [comment]
sorry, I'm not used to BSD and I obviously didn't recognize it in the LICENSE file.

**Comment by mschoettle** [comment]
I actually have the same question. `BSD` is ambiguous and the license text in the repo does not match `BSD-3-Clause` 100% (it's very close though).

Is it `BSD-3-Clause`?

/cc @maribedran
