### ISSUE TITLE
AttributeError: 'ImagingEncoder' object has no attribute 'pushes_fd'

### ISSUE THREAD

**Issue by coanor** [lincolnloop/python-qrcode#140]
on `image.save()`, I got this exception in `/home/api/.pyenv/versions/2.7.13/lib/python2.7/site-packages/qrcode/image/pil.py, line 47`, I can't reproduce it under demo code, but within flask app, it throws 100%, how to fix it?

After I restart my flask app, it works ok! ...

**Comment by maribedran** [comment]
Closing the issue as no further information was provided and the error didn't seem to happen with anyone else.
