### ISSUE TITLE
optimize argument not used in QRCode.add_data

### ISSUE THREAD

**Issue by a1s** [lincolnloop/python-qrcode#143]
According to the docstring, the `optimize` argument to `QRCode.add_data` has the same meaning as the `minimum` argument to `util.optimal_data_chunks` - that is: set the minimal chink length for data optimization.

However, the method code uses this argument only as a boolean and does not pass the numeric value to the underlying utility function.

**Comment by SmileyChris** [comment]
Cheers, fixed and about to push. Marking as dupe of #144
