### ISSUE TITLE
Binary Data not coming through

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [lincolnloop/python-qrcode#148]
I'm able to write Text data using using `qrcode `and decode it using `pyzbar`

However, when I try to push binary data through, no such luck.

Can I not send byte strings in?  Is this an encoder problem or a decoder one?

For now,  I turned my binary data to ASCII for the QR and then decoded ASCII back to binary.  Just checking to see if I can maybe bypass that step.

Thank you again for your hard work on this... it shows.

**Comment by MikeTheWatchGuy** [comment]
Solved this one by changing data into ascii first.

**Comment by Marxpark** [comment]
Hi Mike

im facing the same issue at the moment with the same libs (qrcode and pyzbar). You say that you solved it but it sound as if you changed the data into ascii, made the qr and decoded the qr into ascii -> not actually passing binary? 

If you managed to decode the binary data with pyzbar, please let me know how you managed that.

Thanks
