### ISSUE TITLE
Are images saved automatically?

### ISSUE THREAD

**Issue by Zambi9** [lincolnloop/python-qrcode#152]
When I run:
`img = qr.make_image()`

The default image viewer appears with a title of a BMP file. Does this file gets saved automatically anywhere? I didn't manage to locate it. 

I know I can save it, that's not the question, actually I want to make sure it isn't saved anywhere, or if so, to know where so I could delete it.

**Comment by SmileyChris** [comment]
It only exists in memory until you save it.
