### ISSUE TITLE
pymaging is dead

### ISSUE THREAD

**Issue by smurfix** [lincolnloop/python-qrcode#153]
The "pymaging" library appears to be dead upstream.

Please switch to either PIL/pillow or cairo.

**Comment by SmileyChris** [comment]
pymaging isn't installed for you, it's not the default factory, and it still technically works.

There's no "switching" to pil, qrcode already uses it.

**Comment by iscsrl** [comment]
Fot those who are still looking I fixed installing pymaging like follow:

    pip3 install -e git+git://github.com/ojii/pymaging.git#egg=pymaging
    pip3 install git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png --no-deps
