### ISSUE TITLE
QR Codes with embedded images (Logos) [feature request]

### ISSUE THREAD

**Issue by cgthayer** [lincolnloop/python-qrcode#156]
Been using the library for a while (awesome thanks!) and would like to insert some images in the middle. I think it would be sufficient if we could leave an open space in the middle of the code, then users could use PIL to write whatever they want in the open spot.

E.g. see "qr code logo" search results: https://goo.gl/THxpcE

**Comment by SmileyChris** [comment]
There's nothing to change here. Just put your logo in the middle! It's the error correction that inherently allows the image to still be read independently of the missing part that you'll cut out & replace.
