### ISSUE TITLE
Where is the QR-Code Image ?

### ISSUE THREAD

**Issue by thomakl** [lincolnloop/python-qrcode#159]
Hi

I installed it correctly with Pip and the module works perfectly through the terminal : 
`qr "Some text" > test.png`
The image is in current directory.

However I can't find the image when I try to generate it through python

`import qrcode
img = qrcode.make('Some data here')`

Any suggestions ? Does someone have the same issue ?

**Comment by AntiSnak** [comment]
Hey,
I had the same problems.
You need to add an img.save to generate the image.

>import qrcode
>
>img = qrcode.make("QR text")
>img.save("test2.png", "PNG")

This fixed this for me. Hope its helps you too!

**Comment by shivamdude** [comment]
where will it be saved

**Comment by SmileyChris** [comment]
Thanks for the answers @AntiSnak
