### ISSUE TITLE
installing qrcode 6.0  error

### ISSUE THREAD

**Issue by jianaijun** [lincolnloop/python-qrcode#160]
In 5.3, everything worked fine, 
An error occurred installing qrcode 6.0:

zip_safe flag not set; analyzing archive contents...
Installing qrcode 6.0
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different project name.
Installing qrcode 6.0
Caused installation of a distribution:
UNKNOWN 0.0.0
with a different version.
Got None.
Error: There is a version conflict.
We already have: UNKNOWN 0.0.0

**Comment by llazzaro** [comment]
I have the same error. Which python version did yo use?
