### ISSUE TITLE
Colored image rendered black-white after pasting to qrcode

### ISSUE THREAD

**Issue by Pkuflint** [lincolnloop/python-qrcode#161]
How to reproduce the problem:
1. Generate a qr code using default fill color(fill color is black, back color is white).
2. Paste a color image to the qr code above.
3. Save the pasted qr code.
```python
def make_qrcode(text):
    qr = qrcode.QRCode(version=10, 
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=8,border=4)
    qr.add_data(text)
    qr.make(fit=True)
    return qr.make_image()

with Image.open(r'avatar.jpg') as logo_image:
    origial_qr = make_qrcode('www.baidu.com')
    resized_logo = logo_image.resize((150,150))
    origial_qr.paste(resized_logo)
    origial_qr.save(r'E:\Export Files\qrcode.png')
```

As you could see below, the colored logo is rendered black and white. 
![customqr](https://user-images.githubusercontent.com/8869580/48241113-7fd3d980-e410-11e8-9a53-62651308690a.png)

The original colored image is below:
![avatar](https://user-images.githubusercontent.com/8869580/48241509-384e4d00-e412-11e8-8f75-eea3d0d599ee.jpg)

Workrounds are:
1. Save the qr code first and open it before pasting.
2. Create a new background image and paste the qr code to the background. 

If anyone knows a better solution, please suggest.

**Comment by heuer** [comment]
The returned image is in black / white mode.

```python
>>> origial_qr = make_qrcode('www.baidu.com')
>>> origial_qr.mode
'1'
```

If you convert the image to RGB you should get the expected result (maybe ```make_qrcode``` should return an already converted image):

```python
>>> origial_qr = make_qrcode('www.baidu.com').convert('RGB')
>>> origial_qr.mode
'RGB'
```
