### ISSUE TITLE
Version Selection is wrong for certain string length

### ISSUE THREAD

**Issue by LXMK** [lincolnloop/python-qrcode#164]
Hi, I've noticed that the version is sometimes not selected correctly, depending on length of the string.
ABCDEFGHIJKLMNO1 -> Version 1 (21x21)
ABCDEFGHIJKLMNO12 -> Version1 (21x21)
ABCDEFGHIJKLMNO123 -> Version2 (25x25)
ABCDEFGHIJKLMNO1234 -> Version2 (25x25)
ABCDEFGHIJKLMNO12345 -> Version1 (21x21)
ABCDEFGHIJKLMNO123456 -> Version1 (21x21)

Forcing to Level 1 (fit=False) gives the error:
qrcode.exceptions.DataOverflowError: Code length overflow. Data size (156) > size available (152)

**Comment by LXMK** [comment]
![qr-codes](https://user-images.githubusercontent.com/3952323/50586762-4f8e4180-0e7b-11e9-91db-dc5934b12617.png)

**Comment by LXMK** [comment]
```
qr = qrcode.QRCode(version=1,
                           error_correction=qrcode.constants.ERROR_CORRECT_L,
                           box_size=20,
                           border=2)
        qr.add_data(self.text)
        qr.make(fit=False)
        img = qr.make_image()
```

**Comment by SmileyChris** [comment]
It isn't just the length of the string taken into account, but the contents. Digits can be encoded more succinctly, so when 4 in a row are found, we switch encoding for that block meaning those extra numbers can use less space than encoded as alphanumeric

**Comment by LXMK** [comment]
It has nothing to do with digits! I've just used them for illustrating. It is the same when only letters are used!

**Comment by SmileyChris** [comment]
It was still an issue with mode encoding, the case was just a bit different.
`add_data()` optimizes the chunks of data into the correct mode type, but if the data was shorter than the minimum optimization length, it wasn't attempting to pick the correct mode type -- now it does.
