### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by koutoftimer** [lincolnloop/python-qrcode#166]
Do you have support for python 3.7?

Highest version in `setup.py` is [3.6](https://github.com/lincolnloop/python-qrcode/blob/master/setup.cfg#L20)

**Comment by zifter** [comment]
I've added tests check for 3.7 in #167 and it's passed successfully. I suppose we have no blockers for that.

**Comment by zifter** [comment]
I will make it when #167 will be merged.

**Comment by septatrix** [comment]
Is there anything left to do? Also python 3.8 is out

**Comment by hugovk** [comment]
Also Python 3.9 is out :)

Please see PR https://github.com/lincolnloop/python-qrcode/pull/209.

**Comment by zifter** [comment]
This pr was created more than 1,5 year :) Feedback is so fast! ><
