### ISSUE TITLE
Not scannable QR-Code on macOS console

### ISSUE THREAD

**Issue by Endogen** [lincolnloop/python-qrcode#175]
Hi,

i'm trying to create a QR-Code and show it on the console. It works but shows this
![image](https://user-images.githubusercontent.com/226475/60469513-38c77c80-9c5d-11e9-89fa-6cf5af8573a9.png)

This is my code:
```python
        import qrcode

        qr = qrcode.QRCode()
        qr.add_data("104c7136574c86837069285b6760d53bd029a8a8063c3d4857e01660")
        qr.print_ascii()
```

I'm on macOS 10.14.5 with ZSH and Python 3.7. Not sure if this is related: https://github.com/lincolnloop/python-qrcode/issues/66

**Comment by Endogen** [comment]
After some testing, i can see it working on Windows. Any idea how i can get it working also on macOS with ZSH? Or can someone please test it on macOS without ZSH?

**Comment by Endogen** [comment]
Did some more tests and there is no issue if i create the QR-Code with this module:
https://github.com/mnooner256/pyqrcode

The QR-Code is much larger but works fine
![image](https://user-images.githubusercontent.com/226475/60546789-5a3c6d00-9d1e-11e9-8b80-88644f6fb8cf.png)

My code:
```python
        import pyqrcode

        address = "104c7136574c86837069285b6760d53bd029a8a8063c3d4857e01660"

        qr = pyqrcode.create(address, error="L", version=4)
        print(qr.terminal("black", "white", quiet_zone=2))
```

**Comment by heuer** [comment]
IIRC you can get better results if you use iTerm2.

PyQRCode utilizes ANSI escape to generate the output. This project can do the same if you use the ``QRCode.print_tty()`` method

**Comment by Endogen** [comment]
Thanks for your answer! I see, iTerm2 is some advanced stuff :-) I'm actually pretty happy with ZSH but will look into it 👍 

Nice! Didn't know about `QRCode.print_tty()`. Thanks for that.
