### ISSUE TITLE
AttributeError: module 'qrcode' has no attribute 'make'

### ISSUE THREAD

**Issue by Go-Code-Ren** [lincolnloop/python-qrcode#185]
Error while running a basic program such as that given in the module documentation.

**Comment by heuer** [comment]
A code example would be helpful

I guess you're doing something wrong

Works here:

```python
>>> import qrcode
>>> img = qrcode.make('test')
>>> img
<qrcode.image.pil.PilImage object at 0x7f6504239128>
```

**Comment by Aishwarya19966** [comment]
Probably its path issue 
Try it on the windows command prompt it works fine for me

**Comment by gokulbhaveshjoshi** [comment]
Attribute error: qrcode has no module make()

**Comment by sumit-kushwah** [comment]
For me, I have changed my filename from qrcode to another name

**Comment by Aishwarya19966** [comment]
Yeah exactly don't keep the file name as qrcode.py please change it other name

**Comment by wesley9090980** [comment]
yes  it really works  just change you filename qrcode.py to another name

**Comment by cyjaysun** [comment]
don't keep the file name as qrcode.py
it works !

**Comment by Arshi-mgh** [comment]
For me, this error appears inside the docker. Works fine outside. How do I solve that?

**Comment by Brahmjot09** [comment]
> For me, I have changed my filename from qrcode to another name

and I am guessing why this works ...:grin:

**Comment by Sohaib-radi** [comment]
I just delete an app named qrcode  and this works ... oooohaaaa 💯

**Comment by JaksonCasas19** [comment]
I also had a problem when running the qr pip, I recommend doing a little test in the shell and it worked for me later!

**Comment by bitf17m558** [comment]
I am getting same error where is this qrcode.py file exist

**Comment by ArtemGames06** [comment]
When I wanted to create a qr code, I get an error

AttributeError: partially initialized module 'qrcode' has no attribute 'make' (most likely due to a circular import)

**Comment by jacksonsophat** [comment]
I don't have any file name qrcode.py but it still says ` module 'qrcode' has no attribute 'make' `

**Comment by Riti70912** [comment]
despite changing the name i am getting the same error anyone can help me out

**Comment by M-0326** [comment]
AttributeError: partially initialized module 'qrcode' has no attribute 'QRCode' (most likely due to a circular import). Did you mean: 'qrcode'?                            unable to ressolve..

**Comment by RamennSama** [comment]
I tried for almost an hour and found out that if there is not a file named qrcode.py with the same name as the library, it is probably because you have "pip install django-qrcode" along with "pip install qrcode", so try "uninstall django-qrcode" and run the code:)
