### ISSUE TITLE
Broken dependencies on Windows platform

### ISSUE THREAD

**Issue by aidistan** [lincolnloop/python-qrcode#187]
Thanks for this great package.

I am trying to install `qrcode` on Windows platform with Python 3.4 which is compatible according to [the classifiers](https://github.com/lincolnloop/python-qrcode/blob/master/setup.cfg#L18). However, `colorama` [which is required on Windows](https://github.com/lincolnloop/python-qrcode/blob/master/setup.cfg#L30) has given up Python 3.4 since [v0.4.2](https://pypi.org/project/colorama/0.4.2/).

Could we fix it by specifying a version of `colorama` ?

**Comment by maribedran** [comment]
Closing as we dropped Python < 3.6 support.
