### ISSUE TITLE
Suggestion: Add title parameter

### ISSUE THREAD

**Issue by GadgetSteve** [lincolnloop/python-qrcode#199]
When producing multiple QR codes it is very handy to include in the image some text to describe which one is which, currently the only way to do this is to add the title manually using an image/svg editor or with image magick.

It would be great if there was a --title= parameter that allowed us to specify some text to have centred in the bottom border. An example is attached.
![okta_android](https://user-images.githubusercontent.com/5593690/87576040-b293a200-c6c8-11ea-84b4-5085b1361f55.jpg)

**Comment by angeluisq** [comment]
hi, you have a solution to issue?

**Comment by heuer** [comment]
In my opinion, such a feature is a bit questionable, as QR codes can hold a lot of data. You can also easily do this with Pillow. Here you can find an example, this should be easy to adapt to python-qrcode: https://github.com/heuer/segno/blob/master/examples/qrcode_text/png_text.py

Results:
![a-day-in-the-life-1](https://user-images.githubusercontent.com/364926/92322915-ba225800-f034-11ea-8063-99de2d2cbd6d.png)
![a-day-in-the-life-2](https://user-images.githubusercontent.com/364926/92322918-bdb5df00-f034-11ea-9700-fada413e2f0e.png)
![a-day-in-the-life-3](https://user-images.githubusercontent.com/364926/92322921-c0b0cf80-f034-11ea-98ef-15d35d2453ca.png)
![a-day-in-the-life-4](https://user-images.githubusercontent.com/364926/92322923-c27a9300-f034-11ea-89cd-eba1b3deace7.png)

**Comment by heuer** [comment]
Example to generate an additional text for SVG output: https://github.com/heuer/segno/blob/master/examples/qrcode_text/svg_text.py


![rain-1](https://user-images.githubusercontent.com/364926/92332867-03989480-f081-11ea-919e-a9d248effde2.png)
![rain-2](https://user-images.githubusercontent.com/364926/92332868-03989480-f081-11ea-8a97-f25fa7b28784.png)
![rain-3](https://user-images.githubusercontent.com/364926/92332869-04312b00-f081-11ea-8bc8-7aa3b9f20bd8.png)
![rain-4](https://user-images.githubusercontent.com/364926/92332870-04c9c180-f081-11ea-88ab-2a012fcbb260.png)
![rain-5](https://user-images.githubusercontent.com/364926/92332871-04c9c180-f081-11ea-9cd0-a08c4db40013.png)
![rain-6](https://user-images.githubusercontent.com/364926/92332872-04c9c180-f081-11ea-8e78-e4035ef6f2a1.png)

**Comment by heuer** [comment]
See also https://github.com/lincolnloop/python-qrcode/issues/91

**Comment by kumkaning** [comment]
good

**Comment by kumkaning** [comment]
:sunglasses:
