### ISSUE TITLE
micro qr support

### ISSUE THREAD

**Issue by edwardocano** [lincolnloop/python-qrcode#201]
do you plan to add micro qr to your library?

**Comment by heuer** [comment]
Thanks for the suggestion, but you are on several projects, some of which declared that they are dead offered or provide solutions:

* https://github.com/sylnsfar/qrcode/issues/71* https://github.com/lincolnloop/python-qrcode/issues/201
* https://github.com/dlazaro66/QRCodeReaderView/issues/181
* https://github.com/nayuki/QR-Code-generator/issues/98
* https://github.com/heuer/segno/issues/85

There is not even a common sense on the programming language...  

What you're asking about frankly? We should do  your homework?

**Comment by edwardocano** [comment]
Hi!

I really do not understand what is the problem of being in several projects. If you could explain me please. 
I am asking because i am developing a web based watermarking system, the mark is a qr code, that is why i need a mini qr code, and i just can not stop to develop a mini qr code to the prototype of the system.
