### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by septatrix** [lincolnloop/python-qrcode#206]
Python 2 reached EOL at the beginning of this year and Pillow also stopped supporting it ([reference](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#python-2-7)) in the newest version.

This would allow to get rid of Python 2 specific code and therefore decrease surface for bugs.

**Comment by hugovk** [comment]
Please see PR https://github.com/lincolnloop/python-qrcode/pull/208.

**Comment by maribedran** [comment]
Fixed by #209
