### ISSUE TITLE
the result turns into a rectangle

### ISSUE THREAD

**Issue by Andromeda606** [lincolnloop/python-qrcode#211]
I know it's not the library's fault but is there a way to prevent it

![image](https://user-images.githubusercontent.com/43077625/97489674-e5f4f680-1970-11eb-8fc6-4a5afbfc4b6e.png)

**Comment by Andromeda606** [comment]
in this case the qr code cannot be read and this feature has no function left.

**Comment by eabase** [comment]
Yes, use a different font (without lines above/below) or file an issue report to PyCharm or just install mintty.
