### ISSUE TITLE
AttributeError: 'function' object has no attribute 'make', 'QRCode'

### ISSUE THREAD

**Issue by imvickykumar999** [lincolnloop/python-qrcode#217]
img = qrcode.QRCode(
AttributeError: 'function' object has no attribute 'QRCode'

    img = qrcode.make(data)
AttributeError: 'function' object has no attribute 'make'

...neither of above works in cmd but working in jupyter notebook !!!

**Comment by heuer** [comment]
Probably you've a defined a function which is named "qrcode" in your code. Just rename your function into "make_qrcode" or something like that.

See also #185 for a similar problem

**Comment by maribedran** [comment]
This seems to be answered.
