### ISSUE TITLE
non-PIL variant's dependencies

### ISSUE THREAD

**Issue by mrx23dot** [lincolnloop/python-qrcode#223]
Could we add these dependencies to the PIL free install?

pip install git+git://github.com/ojii/pymaging.git#egg=pymaging
pip install git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png

Or even better something that's already in the repo like:
  pypng

So it would be standalone install:
"pip install qrcode"

On a budget linux SBC I don't have enough memory to install pillow (140MB is not enough..).

**Comment by heuer** [comment]
Shameless plug: Segno comes with no dependencies and can create PNG natively (w/o pypng): https://pypi.org/project/segno/

**Comment by alerque** [comment]
It would be nice if the dependencies actually called all the things that might be needed, even if it's behind as an extra feature or something. An 'extra' isn't exactly optional if it then falls back to assuming something else that's not even listed.

**Comment by couleurwest** [comment]
I am
