### ISSUE TITLE
State of the the project?

### ISSUE THREAD

**Issue by jensens** [lincolnloop/python-qrcode#227]
Hi, this project looks like it is stalled. 
I see lots of issues and worth-to-merge pull requests. But no commits since 16 months.
So, its a valuable project, sad if its abandoned.

My questions: 

- What is the reason for dropped activity of the maintainers? 
- Is there an active fork I should know?
- Or is there another project which is now the new standard I should know of?
- If not, what can we do to make it move on? (like insert coin to continue, help to move to community driven project, ...)

Thanks for any insights!

**Comment by klausmcm** [comment]
I'm currently looking to adjust some of the code in https://github.com/hudora/huBarcode to make generating barcodes for given length constraints easier. I'm using `numpy` and `pint` for flexible resizing of the barcodes and have the code working for Code128 barcodes and want to do something similar for Data Matrix barcodes. There seemed to be some issues with QR codes in the `huBarcode` package. Maybe it's time to create single package again that combines the barcodes in `huBarcode` and the QR barcodes from here?

**Comment by SmileyChris** [comment]
Hi @jensens -- the main reason is that other paid work has been sapping 100% of my tim.
I'm more than happy to bring on some additional contributors.

**Comment by heuer** [comment]
Shameless plug <https://github.com/heuer/segno> ;)
No dependencies, a lot of serialization formats w/o Pillow

**Comment by SmileyChris** [comment]
And yes, segno is pretty awesome ^

**Comment by klausmcm** [comment]
@SmileyChris, @heuer Are either of you open to include other barcode types in your package?

**Comment by heuer** [comment]
> And yes, segno is pretty awesome ^

Thank you, I didn't mean to get in your way. I am happy that you are still active here.

**Comment by heuer** [comment]
> @SmileyChris, @heuer Are either of you open to include other barcode types in your package?

I can't speak for Lincolnloop, I'm not currently planning any further support for any other barcodes.

You are probably in better hands here <https://github.com/WhyNotHugo/python-barcode> than at <https://github.com/hudora/huBarcode> when you need a wide range of barcodes. It supports no QR Codes, though.

**Comment by maribedran** [comment]
@jensens I'll be helping manage the project for a while as @SmileyChris doesn't have the time to do it for now. I'm not familiar with the code, though, so I'd like some help looking at the more complex PRs. We just released version 7.0 dropping Python 2 support and upgrading to 3. I've been merging some of the small PRs and will release a 7.1 version with those features. The ones that add more changes to the code base will need more time to review.
