### ISSUE TITLE
[New feature request] Add image into QR code.

### ISSUE THREAD

**Issue by water5** [lincolnloop/python-qrcode#232]
Can I add image into QR code like below?

![Image](http://www.image-share.com/upload/4167/74.jpg)

**Comment by KmolYuan** [comment]
You can just use PIL's method if the image factory is `PilImage`, which is the default factory. In that case, `my_qrcode` is `Image` type as well.

```python
import qrcode
from PIL import Image

my_qrcode = qrcode.make("Some data here")

image = Image.open('image.jpg')
image = image.resize((w, h))  # Resize before you paste!

my_qrcode.paste(image,(0,0))
my_qrcode.save("my_qrcode.jpg")
```

**Comment by maribedran** [comment]
You can also use the new styled PIL image factory and embed an image directly: https://github.com/lincolnloop/python-qrcode/blob/master/README.rst#styled-image

**Comment by water5** [comment]
Why `paste` not appear in `dir(my_code)`?

**Comment by maribedran** [comment]
I didn't understand the question. Can you elaborate? Maybe show the code you're trying.

**Comment by water5** [comment]
1. Refer:
https://github.com/lincolnloop/python-qrcode/issues/232#issuecomment-882525215

`import qrcode`
`qr = qrcode.make('embeded image test')`

Why `paste` not appear in
`dir(qr)` ?

2. I try:

`import qrcode`
`from qrcode.image.styledpil import StyledPilImage`

`qr = qrcode.QRCode()`
`qr.add_data('insert image into qrcode test')`
`img = qr.make_image(image_factory = StyledPilImage, embeded_image_path = 'test_image.png')`

The two ways above, the image just override origin qrcode pixel, not 'embeded', so it can't Recognition,

![Image](https://imgshare.io/images/2021/07/19/28daeccfaabd41a6d.png)

![Image](https://imgshare.io/images/2021/07/19/18317d7bbbc094d81.png)

**Comment by KmolYuan** [comment]
> Why `paste` not appear in `dir(qr)`?

The qrcode object is actually the `PilImage` class, but it overrides `__getattr__` magic method used to wrap the PIL image instance.

For overlay a transparent image, these methods should help. Please try to make the two pictures into the same mode via [`Image.convert`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert), such as RGBA.

+ [`Image.paste`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste) (mask option)
+ [`Image.alpha_composite`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.alpha_composite)

**Comment by water5** [comment]
Solved, reduce embed image size and set higher error correction level.
