### ISSUE TITLE
Attribute error while launching the script

### ISSUE THREAD

**Issue by xatarox** [lincolnloop/python-qrcode#233]
import qrcode
qr = qrcode.QRCode(
    version=1,`
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data('Some data')
qr.make(fit=True)

img = qr.make_image(fill_color="black", back_color="white")

Traceback (most recent call last):
  File "C:\Users\vodax\Desktop\qrcode.py", line 1, in <module>
    import qrcode
  File "C:\Users\vodax\Desktop\qrcode.py", line 2, in <module>
    qr = qrcode.QRCode(
AttributeError: partially initialized module 'qrcode' has no attribute 'QRCode' (most likely due to a circular import)

**Comment by AndiEcker** [comment]
rename the file `C:\Users\vodax\Desktop\qrcode.py` to something else like `
*qrcode*.py`

Am Sa., 7. Aug. 2021 um 01:43 Uhr schrieb ATAR ***@***.***>:

**Comment by xatarox** [comment]
Thank you so much, what a stupid error of mine !
:)
