### ISSUE TITLE
Decode QRCode from a PNG is not possible

### ISSUE THREAD

**Issue by Hierosme** [lincolnloop/python-qrcode#238]
Hello look, the actual code not have capability to Read a QRCode from a png file.

I have confirm that by read every unittest.

Only Type BytesIO , PIL.Image,  StringIO are tested. Never the encoded data is verify by a Encode/Decode

Unfortunally it writing a tools use python-qrcode lib and that is imposible to write a unittest and get back my data after a Encode/Decode.

Please consider to follow Issues and Pull Requests, because actually it have not value to contribute to python-qrcode

**Comment by SmileyChris** [comment]
QRCode is solely a QR code generator, not a QR code reader.
