### ISSUE TITLE
Print QR Code in text based

### ISSUE THREAD

**Issue by ronnifadhlillah** [lincolnloop/python-qrcode#242]
Hallo !... anyone can help me to print QR code in text not in image format.

the sample below is if i generate qrcode with print_ascii from console
![image](https://user-images.githubusercontent.com/33772449/139553907-5b8824a4-7e3d-4a00-8b8d-c5e198d1abef.png)

by the way, thank you :)

**Comment by hvitis** [comment]
Hey, 

that's wrong forum to ask this question.
Try using this: http://asciiqr.com/index.php

**Comment by ronnifadhlillah** [comment]
okay. thank you for your respond..
