### ISSUE TITLE
Use different mask pattern in Format String

### ISSUE THREAD

**Issue by dbarrerap** [lincolnloop/python-qrcode#251]
According to [this documentation](https://www.thonky.com/qr-code-tutorial/format-version-tables), the format string consists of ECC Level and a Mask Pattern. Doing some tests, the implementation of ERROR_CORRECT_H uses Mask Pattern 2.

Is there a way to modify the Mask Pattern used in order to use a specific Format String?

**Comment by heuer** [comment]
The mask pattern depends on the data, see <https://www.thonky.com/qr-code-tutorial/data-masking> 
You shouldn't assume that a Qr code using error level H uses always mask pattern 2.

However, it is possible to specify the mask pattern:

````
qr_img = qrcode.make(data='Test', mask_pattern=3)
````

Please note that this may lead to a QR code which uses an unoptimized layout. As stated above the mask pattern depends on the data and masking ensures that the QR code is easily readable.

**Comment by dbarrerap** [comment]
Thanks for this information, I didn't read the part you sent. I'll close this issue.
