### ISSUE TITLE
I'm guessing you're using Django. So something like this:

### ISSUE THREAD

**Issue by Rohit685** [lincolnloop/python-qrcode#259]
I'm guessing you're using Django. So something like this:
```python
from qrcode import make
from django.contrib.staticfiles.storage import staticfiles_storage

qr = make(QRUrl)
with staticfiles_storage.open('myqr.png') as f:
    qr.save(f)
```

__Originally posted by @SmileyChris in https://github.com/lincolnloop/python-qrcode/issues/258#issuecomment-1038381045__

What if I'm using Flask?

**Comment by SmileyChris** [comment]
Then use the same method but with however you create a filelike object to your static files location.

**Comment by Rohit685** [comment]
ok. I will try to find something like staticfiles_storage that is usable in Flask. Is there any other way of doing it?

**Comment by Rohit685** [comment]
I think i figured it out
thank you
