### ISSUE TITLE
How to use attrib parameter in make_image()? 

### ISSUE THREAD

**Issue by Jaironlanda** [lincolnloop/python-qrcode#261]
Hi, 

There is any guide/tutorial that I can refer about `attrib` parameter in `make_image()`?

**Comment by SmileyChris** [comment]
Parameters are passed to the underlying image object. If you're using `attrib` then it must be an SVG which is using [ElementTree.Element](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element) object.

**Comment by Jaironlanda** [comment]
Thank you for reply. 

I installed this library from here (https://pypi.org/project/qrcode/7.3.1/), but the `attrib` parameter is not working. To solve this problem, I cloned the main repository.
