### ISSUE TITLE
QR codes unreadable

### ISSUE THREAD

**Issue by bridger** [lincolnloop/python-qrcode#263]
Something seems to have recently broken.

QR codes made with this commit work: https://github.com/lincolnloop/python-qrcode/commit/f63dc2b5f6a6e4a128cd13100c4a720e98a3b39a
QR codes made with this later commit don't scan: https://github.com/lincolnloop/python-qrcode/commit/3a67d072d63879941db5aae91d0b1db745d140ba

Here is the code I'm using to create the QR code. I don't know if this is specific to the SVG drawer or is more general.
```
import qrcode
import qrcode.image.svg
img = qrcode.make("https://scribbletogether.com", image_factory=qrcode.image.svg.SvgPathImage)
```

**Comment by bridger** [comment]
Here is an example of the broken QR:
![BrokenQR](https://user-images.githubusercontent.com/1337793/158031319-a14357f2-c1e8-416d-931f-6f2a18e3b603.svg)

**Comment by SmileyChris** [comment]
Apologies, and thanks for being my sanity check 🥇
