### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by SOLOMONCHIKEZIE** [lincolnloop/python-qrcode#270]
raceback (most recent call last):
  File "C:\Users\hp\PycharmProject\pythonProject\QRcode\qrcode.py", line 1, in <module>
    import qrcode
  File "C:\Users\hp\PycharmProject\pythonProject\QRcode\qrcode.py", line 2, in <module>
    qr = qrcode.QRCode(
AttributeError: partially initialized module 'qrcode' has no attribute 'QRCode' (most likely due to a circular import)

**Comment by SOLOMONCHIKEZIE** [comment]
please I need help

**Comment by SmileyChris** [comment]
Don't call your module `qrcode.py`. It can't import the `qrcode` package.

**Comment by heuer** [comment]
This error is so common, maybe it should be mentioned in the README?
* <https://github.com/lincolnloop/python-qrcode/issues/233>
* <https://github.com/lincolnloop/python-qrcode/issues/218>
* <https://github.com/lincolnloop/python-qrcode/issues/217>

Just to name a few. ;)
