### ISSUE TITLE
choose `alphanumeric`, `bytes`, `kanji` or `numeric` encoding modes?

### ISSUE THREAD

**Issue by vistuleB** [lincolnloop/python-qrcode#272]
The QR code standard supports four different encoding formats, from my understanding, as enumerated in the title.

Does this package allow to select the encoding? For example, "ABCDEF" might be either encoded in UTF-8 (bytes) with 6 bytes, or in "alphanumeric" mode with 3 x 11 bits. A string like "1234" even affords 3 different encodings: UTF-8 (bytes), alphanumeric, and numeric, resulting in different QR codes.

How does one select the encoding?

**Comment by SmileyChris** [comment]
You can't manually select the encoding, but Numeric, Alphanumeric, utf-8 modes are automatically selected based on the input data provided. The data is also automatically chunked into different minimum encoding types of at least the number of characters matching the integer `optimize` argument.

Kanji isn't currently supported.
