### ISSUE TITLE
No module named 'qrcode.image.styles.moduledrawers.pil'

### ISSUE THREAD

**Issue by ewwachter** [lincolnloop/python-qrcode#278]
Dear,

I have both pil and qrcode installed:
```
Requirement already satisfied: qrcode[pil] in /usr/local/lib/python3.8/dist-packages (7.3.1)
Requirement already satisfied: pillow; extra == "pil" in /usr/local/lib/python3.8/dist-packages (from qrcode[pil]) (9.2.0)
```

But I'm getting this error:
No module named 'qrcode.image.styles.moduledrawers.pil'

Do you know what is the issue here?

**Comment by famesjranko** [comment]
In case anyone else comes across this, I had a similar issue with importing RoundedModuleDrawers:

The readme shows: 
```python
from qrcode.image.styles.moduledrawers.pil import RoundedModuleDrawer
```
But the correct import is actually:
```python
from qrcode.image.styles.moduledrawers import RoundedModuleDrawer
```

**Comment by SmileyChris** [comment]
readme should be correct now that new version has been released
