### ISSUE TITLE
Is it possible to generate QR code with 2 colors?

### ISSUE THREAD

**Issue by alperiox** [lincolnloop/python-qrcode#280]
Is it possible to generate QR codes with more than 1 foreground color with this package? like the image [here](https://i.imgur.com/EL00e6e.png)?

**Comment by heuer** [comment]
Acc. to my knowledge it is not possible.

That particular image was generated by Segno see https://segno.readthedocs.io/en/stable/colorful-qrcodes.html

**Comment by alperiox** [comment]
Yeah, I know it is possible with Segno. I've wondered if it is possible with qrcode too, thanks for the answer!

**Comment by xtream1101** [comment]
@alperiox I wanted this feature too. I kept it simpler then your example and just allow the main data be one color and then the eye/location marker can have 2 colors. This repo is like a plugin for this qrcode library that has custom module_drawers to pass in.

If you wanted to check it out https://github.com/xtream1101/qrcode-xcolor
