### ISSUE TITLE
ModuleNotFoundError: No module named 'Image'

### ISSUE THREAD

**Issue by YueLiXing** [lincolnloop/python-qrcode#281]
- Python 3.9.13
- pip 22.2.2 

user `pip3 install qrcode` install qrcode.

![image](https://user-images.githubusercontent.com/9456800/183608375-ce88171e-f6c3-4a6f-9fe3-5fe30499d899.png)

but not found

![image](https://user-images.githubusercontent.com/9456800/183608106-0ef3616f-4daa-486f-b934-d6df720c0c1d.png)

**Comment by Raam124** [comment]
just install pillow separately `pip install Pillow`

**Comment by bnlcas** [comment]
This does feel like a bug. If there is any interest I would be happy to patch in a PR to resolve this dependency in the installation.

**Comment by SmileyChris** [comment]
`zsh` has special meanings for square brackets -- you'll have to escape them (either with quotes `pip install "qrcode[pil]"`, or with a leading slash `pip install qrcode\[pil\]`)

Alternatively, you could add this to your `.zshrc`:
```
alias pip='noglob pip'
```

**Comment by bnlcas** [comment]
@SmileyChris - thank you for the explanation here (learn something new everyday). Would it be possible to make an edit to this effect in setup instructions in the Readme file? This feels like it is going to be a common stumbling point for anyone following the setup instructions on a Mac.

**Comment by SmileyChris** [comment]
Yep that seems like a good idea, do a pull request to put quotes around that in the readme. 👍
