### ISSUE TITLE
Is there a way to use this module to create QR codes with images in the center?

### ISSUE THREAD

**Issue by MCUxDaredevil** [lincolnloop/python-qrcode#283]
I am trying to create QR codes that contain a logo at their center. Something like this:

![image](https://user-images.githubusercontent.com/59441946/187506232-9e96dd5f-7506-4f8f-9699-7cadce91420c.png)

Is it possible to do so using this library? I know there are already multiple ways to manipulate the design but not sure if this is one of them.

**Comment by rousseldenis** [comment]
I have the same requirements

**Comment by bennychee** [comment]
https://medium.com/codestorm/how-to-create-qr-code-using-python-2094dc7e3db6

**Comment by MCUxDaredevil** [comment]
> https://medium.com/codestorm/how-to-create-qr-code-using-python-2094dc7e3db6

Thanks a lot!
