### ISSUE TITLE
there is the command the last 

### ISSUE THREAD

**Issue by mariia993** [lincolnloop/python-qrcode#285]
def _check_box_size(size):
    if int(size) <= 0:
        raise ValueError(f"Invalid box size (was {size}, expected larger than 0)")
there too many commands, and it si look like the code  hadn't been finished. 
if int(size) <= 0:
ther is the gap.
        raise ValueError
    if int(size) <= 0:
you should write the code like the Java.

**Comment by SmileyChris** [comment]
This is the code being referenced:
https://github.com/lincolnloop/python-qrcode/blob/7eb16aea7bccd2df38c6f0cb45e19ff7cf73a2b9/qrcode/main.py#L32-L36

...but I have no clue what this issue is asking. Closing until it makes sense.

**Comment by mariia993** [comment]
stop following me, dutch.

ср, 5 окт. 2022 г. в 23:26, Chris Beaven ***@***.***>:

**Comment by mariia993** [comment]
I'm pregnant. from the pork.


ср, 5 окт. 2022 г. в 20:31, Mariia Kyianytsia ***@***.***>:

**Comment by mariia993** [comment]
its really tasty, bimack from the pork. or cabbage soup like from crime and
punishment.

ср, 5 окт. 2022 г. в 20:33, Mariia Kyianytsia ***@***.***>:
