### ISSUE TITLE
About installed script, "command not found: qr" 

### ISSUE THREAD

**Issue by itstartstosnow** [lincolnloop/python-qrcode#298]
Hello, 

I just installed this package (Mac OS Monterey 12.5.1), but the `qr` command cannot be found in my command line (zsh or bash). 

Still, the python package can be imported and works well. 

```
[~]$ qr
zsh: command not found: qr

[~]$ python3
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qrcode 
>>> img = qrcode.make("test")
>>> img.show()
```

I wonder where is the `qr` file? Did I miss any step in installation? 

Thank you very much!

**Comment by SmileyChris** [comment]
Pip installs this in your local python bin folder. Perhaps that's not in your path?
