### ISSUE TITLE
Adding logo removes data from the QR code

### ISSUE THREAD

**Issue by ethanj20** [lincolnloop/python-qrcode#299]
When I add the logo, rather than the QR code rearranging such that all the relevant data is still contained, it just replaces that portion of the image. Therefore, a lot of my QR codes with logos are not readable because they don't have enough of the information needed to transmit the code. 

Suggested fix: when adding a logo, rearrange the pixels of the code such that the logo is not blocking key information and the QR codes remain readable.

**Comment by SmileyChris** [comment]
Yes, adding a logo over a QR code removes data, but the code should still be readable thanks to built in error correction. Use a higher error correction level or smaller logos for your QR codes. You can't just "rearrange the pixels".
