### ISSUE TITLE
Version 7.4 can not generate correct qrcode with url length >= 123

### ISSUE THREAD

**Issue by gtxx3600** [lincolnloop/python-qrcode#304]
tried version 7.3.1 and everything works fine

**Comment by mattiasj-axis** [comment]
Can confirm, this reproducer fails to scan:

```
import qrcode
qr = qrcode.QRCode(version=8)
qr.add_data("This is a test")
qr.make()
qr.print_ascii(invert=True)
```
version <= 7 will scan
version >= 8 will not scan (tested up to 10)

**Comment by mattiasj-axis** [comment]
Bisect says f2fee0ae63c49663922bf5827ef8ec024b1df312 is the fault commit

Reverting the changes to create_bytes to how it looked before that commit solves the issue.

**Comment by iulica** [comment]
That was a bugger, yesterday 100 bills went away with a bad QR code. Please release a fix soon, or remove the buggy version.

Thanks for fixing

**Comment by SmileyChris** [comment]
Yikes! Apologies for this bug. If someone wants to write some test against some larger qr code sizes with their expected results, that might be useful to avoid such a regression again...

I yanked the v7.4 release from pypi and just pushed the fix from @mattiasj-axis as v7.4.1

**Comment by qxsch** [comment]
@iulica  i could work around this with segno. now qr code generation for bills is running stable again.

**Comment by iulica** [comment]
> 

Thanks, for me it was just installing the previous version. Unfortunately I haven't checked the bills before sending, as they looked quite fine visually. Lesson learned, next time I will quickly check them before sending :). Anyway, thanks for the quick fix and the new version.

Kind regards
