### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by Nicolalorettu** [lincolnloop/python-qrcode#306]
I tried the library in both linux vm and windows 11 with the same results

import qrcode 
img = qrcode.make("https://www.youtube.com/")
img.save("youtubeQR.jpg")

**Comment by texnofobix** [comment]
I had to install `pip install qrcode[pil]`, and it worked. Looks like it should work without it, so the issue is valid.

**Comment by SmileyChris** [comment]
This should work now without pil (although it'll be a png file even if you called it `"something.jpg"`) in the version I just released.

Previously the pure png factory needed :
```python
with open("youtubeQR.jpg", "wb") as f:
    img.save(f)
```
