### ISSUE TITLE
Unable to create svg qrcode with version > 7.4

### ISSUE THREAD

**Issue by obriand1** [lincolnloop/python-qrcode#310]
Line : 
QRimg = QRcode.make_image(
    image_factory=qrcode.image.svg.SvgImage,
    module_drawer=SquareModuleDrawer(),
)
generate the following error message:
File "/home/obriand/.pyenv/versions/qrcode/lib/python3.11/site-packages/PIL/ImageDraw.py", line 62, in __init__
    im.load()
    ^^^^^^^
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'load'

When I reinstall version 7.3.1, everything is ok

**Comment by akx** [comment]
`SquareModuleDrawer()` is meant to be used with PIL. Use `SvgSquareDrawer()` for SVGs.
