### ISSUE TITLE
How long is the QR code image going to be valid?

### ISSUE THREAD

**Issue by coolzzing** [lincolnloop/python-qrcode#336]
Hi,

My wife got free QR code from online but it turned out free trial is expired. And fortunately I found this repo and generated one free. I wonder if the QR code image I generated here would have such free trial period or would be permanently free to use.

**Comment by ronytesler** [comment]
The content encoded in a QR code is always valid.

**Comment by kmacdough** [comment]
> The content encoded in a QR code is always valid.

Exactly. This generates a QR code that contains the actual WiFi info. This should last indefinitely, although standards sometimes change over the decades.

Your previous QR code must have linked to the shady website instead, which stored your WiFi credentials on its server.

**Comment by bartTC** [comment]
Thank you for the clarification.
