### ISSUE TITLE
3.12 qr cli: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by imba-tjd** [lincolnloop/python-qrcode#348]
As of Python 3.12, distutils has been removed. However `qrcode/console_scripts.py` uses `pkg_resources`. The temporary fix is `pip install setuptools`.

![图片](https://github.com/lincolnloop/python-qrcode/assets/24759802/cc1849c6-b913-479a-b470-be3f350f3cc4)

**Comment by astrojuanlu** [comment]
Now this affects installations without `setuptools` in general, for example those created by `uv venv`.

**Comment by fmleo** [comment]
this also affects installations using poetry

**Comment by imba-tjd** [comment]
fixed by https://github.com/lincolnloop/python-qrcode/pull/370
