### ISSUE TITLE
No module named 'qrcode' HELP PLEASE!

### ISSUE THREAD

**Issue by Strangercmd** [lincolnloop/python-qrcode#366]
![Screenshot 2024-07-16 115052](https://github.com/user-attachments/assets/dcae540b-b615-47ab-8d2d-1fd7910a6817)

How to fix this please!!

**Comment by M-0612** [comment]
Did you install the module before using
`pip install qrcode`  ?

**Comment by Strangercmd** [comment]
Thank You!
