### ISSUE TITLE
Can export eps format qrcode?

### ISSUE THREAD

**Issue by wingyiu** [lincolnloop/python-qrcode#51]
rt

**Comment by mfrasca** [comment]
aren't you interested in this addition?  after all, postscript is just text, it shouldn't be that difficult using the existing code for SVG and adapt it to EPS.

**Comment by SmileyChris** [comment]
@mfrasca if you want to put together a pull request, I'm happy to merge it in. It seemed like this issue was originally more of a query than a request.

**Comment by mfrasca** [comment]
reducing the task to the very core, let me check the requirement for this new `EpsImage`
- derived from `BaseImage`,
- constructor invoked with three parameters which I can happily ignore, as long as I pass them further to the base class,
- implements methods
  - `drawrect`, for adding a black element in the code,
  - `save`, writing the result to a stream,
  - `new_image`, restarting the object.

what is the role of `units` ?

**Comment by mfrasca** [comment]
it does produce postscript, and the result is recognizable as a QR code for the given input, but it's really just some junk put together which I hope you will see as a base for discussion.
