### ISSUE TITLE
Reading of stdin with non-UTF-8 characters fails with Python 3

### ISSUE THREAD

**Issue by Arfrever** [lincolnloop/python-qrcode#67]
Reading of stdin with non-UTF-8 characters with Python 3 triggers `UnicodeDecodeError` exception:
```
$ echo $'\x80' | PYTHONPATH="." python3.4 qrcode/console_scripts.py
Traceback (most recent call last):
  File "qrcode/console_scripts.py", line 65, in <module>
    main()
  File "qrcode/console_scripts.py", line 50, in main
    data = sys.stdin.read()
  File "/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

Fix:
```
--- qrcode/console_scripts.py
+++ qrcode/console_scripts.py
@@ -47,7 +47,7 @@
     if args:
         data = args[0]
     else:
-        data = sys.stdin.read()
+        data = (sys.stdin.buffer if sys.version_info[0] >= 3 else sys.stdin).read()
     if opts.optimize is None:
         qr.add_data(data)
     else:
--- qrcode/tests/test_script.py
+++ qrcode/tests/test_script.py
@@ -1,3 +1,4 @@
+import sys
 try:
     import unittest2 as unittest
 except ImportError:
@@ -30,7 +31,7 @@
         mock_stdin.configure_mock(**{'read.return_value': 'testtext'})
         with mock.patch('sys.stdin', mock_stdin) as stdin:
             main([])
-            self.assertTrue(stdin.read.called)
+            self.assertTrue((stdin.buffer if sys.version_info[0] >= 3 else stdin).read.called)
         mock_print_ascii.assert_called_with(tty=True)
 
     @mock.patch('os.isatty', lambda *args: True)
```

**Comment by welshjf** [comment]
+1. I don't like that the unit test basically just duplicates the code, but I couldn't work out anything better.

I think Chris would appreciate if you submit these as pull requests.

**Comment by SmileyChris** [comment]
Yes to pull request :)  There's some related code that defines `buff = sys.stdout.buffer` so you might want to shift that to happen within the same conditional and rename the vars to be more explicit (`outbuff` / `inbuff` maybe).

The test doesn't actually *test* for the problem though... it'd be good if we can come up with (even if it's a weird mock) a test case that fails at the moment, and would work after the changes are applied.

**Comment by welshjf** [comment]
Problem is it's the stdin.read() itself that fails. I don't know how you can test that from within Python -- if you mock it out, you remove the problem. Mocking stdin.buffer doesn't work -- stdin.read() continues to use the real file descriptor. Seems like a case for a system/functional test rather than a unit test.

**Comment by SmileyChris** [comment]
Tested it by mock raising a `UnicodeDecodeError` response in python 3 from `sys.stdin.read()` ;)

**Comment by welshjf** [comment]
Just seems to me like a more complicated way of asserting sys.stdin.read wasn't called ;)

**Comment by SmileyChris** [comment]
sure, but it raising exceptions is fun :)
