### ISSUE TITLE
QR-decoding?

### ISSUE THREAD

**Issue by kramer65** [lincolnloop/python-qrcode#72]
I've got an image which I want to decode using Python. Is this python qr-code lib only for generating qr-code images, or also for decoding?

If this doesn't decode images, would you have a tip on which library I can use to decode the images? I'm having a hard time to decode the images in Python. All tips are welcome!

**Comment by pik** [comment]
Why did this get closed?

**Comment by SmileyChris** [comment]
@pik because it's not something anyone is actively working on and isn't part of the primary goal of qrcode. Easy to reopen if someone wants to spearhead the effort though.
