### ISSUE TITLE
qr command line tool generate a file named <stdout> and a zero byte file

### ISSUE THREAD

**Issue by dawncold** [lincolnloop/python-qrcode#88]
my Python is 2.7.6
my Pillow is 3.0.0
OS: ubuntu 14.04 LTS

command: `qr '123' > 1.png`

I got a zero byte file: `1.png` and another file:`<stdout>` which content is what I type

**Comment by dawncold** [comment]
That's the PIL 3.0.0 bug, and will be fixed in 3.1.0

[https://github.com/python-pillow/Pillow/issues/1575](https://github.com/python-pillow/Pillow/issues/1575)

**Comment by SmileyChris** [comment]
Good to know! Thanks for following up, @dawncold
