### ISSUE TITLE
Using a StringIO instead of saving to a file.

### ISSUE THREAD

**Issue by encompass** [lincolnloop/python-qrcode#89]
I am hoping to convert your images to base64 png's in a web application.
However, I can't seem to get it working.

    png_image_buffer = cStringIO.StringIO()
    img.save(png_image_buffer)
    encoded_image = base64.b64encode(png_image_buffer.getvalue())

Could it be that there is no support for doing it this way?  I want to avoid having to right and then delete so many files in my project if I keep having to save them.

**Comment by SmileyChris** [comment]
You haven't explained the problem you are having at all.

I'm doing nearly exactly the same as your example code in a Django project and it works fine.
