### ISSUE TITLE
Wrong capacity on version 15, H codes

### ISSUE THREAD

**Issue by drigz** [lincolnloop/python-qrcode#99]
An error in [qrcode/base.py:120](https://github.com/lincolnloop/python-qrcode/blob/b79ab5b3e5989d6b0f13c2737c9ee8424b4dd21f/qrcode/base.py#L120) reduces the capacity of version 15 H QR codes. The correct values are on page 40 of the QR code ISO spec:

![image](https://cloud.githubusercontent.com/assets/632207/14852520/188af69a-0c87-11e6-825a-ca354e70fc6d.png)

**Comment by welshjf** [comment]
Nice find @drigz. Do you know the implications -- producing unreadable codes? Failing to read valid codes? And are you planning to submit a PR?

For the archaeologists out there, this goes back to https://github.com/unapiedra/pyqrnative/commit/e020eccb85b12b61a8795288dafc900aabeddf84 aka http://pyqrnative.googlecode.com/svn/trunk/pyqrnative/src@3. I've compared to the original qrcode.js from whence that was ported, and this is the only difference in RS_BLOCK_TABLE.
